spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.docker.compose.enabled=false
spring.flyway.enabled=true

app.jwtSecret=yoursecretkeyyoursecretkeyyoursecretkey
app.jwtExpirationMs=900000
app.jwtRefreshExpirationMs=604800000
app.cookieSecure=false
app.cookieSameSite=Strict
app.corsAllowedOrigins=http://localhost:4200
app.businessTimeZone=Africa/Cairo
